sudo: required
dist: trusty
language: cpp

install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools #install necessary Qt files

script:
  - qmake QtTest.pro #we gonna compile for actual program
  - make
  - ./QtTest #run unit test